name: bot

services:
  nginx:
    container_name: nginx
    image: nginx:1.25.0
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
    networks:
      - bot-network

  php:
    container_name: php
    build:
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cached
    networks:
      - bot-network

  mysql:
    container_name: mysql
    image: mysql:8.3.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-bot}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/mysql/
    networks:
      - bot-network

volumes:
  db_data:
    driver: local

networks:
  bot-network:
    driver: bridge
